feat: customize dictionary's fullindex option with metadata.toml
xiaoyifang/goldendict-ng pull request #1000
Opened 2023-07-24 15:55 UTC by xiaoyifang

fix #995

2023-07-25 02:21 UTC, shenlebantongying commented
The "FullIndex" is too weird. It should be "Full-text search" (fts)

Nobody uses the word "fullindex" https://www.google.com/search?q="fullindex"

2023-07-25 02:22 UTC, shenlebantongying requested changes

2023-07-25 02:22 UTC, shenlebantongying commented on website/mkdocs.yml
> +      - Customize Dictionary Name: custom_dictionary.md
```suggestion
      - Customize Dictionary: custom_dictionary.md
```

The title is the first part, the second part will decide url,

2023-07-25 02:38 UTC, shenlebantongying requested changes

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +fullindex=false
```suggestion
fts=false
```

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +this `fullindex` field's value can be on/off, 1/0 ,true/false etc.
```suggestion
this `fts` field's value can be on/off, 1/0 ,true/false etc.
```

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +fullindex=false
```suggestion
fts=false
```

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +## Disable the fullindex of the dictionary
```suggestion
## Disable full-text search for certain dictionary
```

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +will disable the current dictionary's fullindex feature.
```suggestion
will disable the current dictionary's full-text search.
```

2023-07-25 02:38 UTC, shenlebantongying commented on website/docs/custom_dictionary.md
> +you can check the fullindex feature on each dictionary info dialog.
```suggestion
you can check the full-text search on each dictionary's info dialog.
```

2023-07-26 02:02 UTC, xiaoyifang commented on src/ui/dictinfo.cc
> +                                                  QPixmap( ":/icons/fts_disabled.svg" ) );
image seems more eye-catching.but text can do .

2023-07-26 02:03 UTC, merged